# Collections
collections:
  authors:
    output: true


# GitHub pages
title: "Jekyll Test"
url: "https://danielthefletch.github.io"
baseurl: "/jekyll-test"


# Front matter defaults
defaults:
  - scope:
      path: {{baseurl}}
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: {{baseurl}}
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: {{baseurl}}
    values:
      layout: "default"