# Collections
collections:
  authors:
    output: true

# Front matter defaults
defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"

# GitHub pages configuration
domain: danielthefletch.github.io
url: https://danielthefletch.github.io
baseurl: /jekyll-test/_site/